version: '2.2'

services:
  nginx:
    image: nginx:alpine
    container_name: connection-info-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-proxy-config.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - headers-service
    networks:
      - webnet

  headers-service:
    image: python:3-alpine
    container_name: headers-service
    command: python /app/simple-headers-server.py
    volumes:
      - ./simple-headers-server.py:/app/simple-headers-server.py
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
